# Copyright 2026 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

import json
import logging
import os
import threading
from datetime import datetime, timezone

import kombu
from kombu.mixins import ConsumerMixin

logger = logging.getLogger(__name__)

# Fallback location of the XIVO_UUID export, installed by the wazo-uuid package.
XIVO_UUID_FILE = '/etc/profile.d/xivo_uuid.sh'


def find_xivo_uuid(config_uuid=None):
    """Resolve the engine's UUID, used to match every locally-generated event.

    Order: explicit config value, then the XIVO_UUID environment variable,
    then the xivo_uuid.sh profile script (present when run outside a login
    shell, e.g. from systemd).
    """
    if config_uuid:
        return config_uuid
    env_uuid = os.environ.get('XIVO_UUID')
    if env_uuid:
        return env_uuid
    try:
        with open(XIVO_UUID_FILE) as f:
            for line in f:
                line = line.strip()
                if line.startswith('export XIVO_UUID='):
                    return line.split('=', 1)[1].strip().strip('\'"')
    except OSError:
        pass
    return None


class _EventConsumer(ConsumerMixin):
    def __init__(self, connection, exchange, arguments, on_message):
        self.connection = connection
        self._exchange = exchange
        self._arguments = arguments
        self._on_message = on_message

    def get_consumers(self, Consumer, channel):
        queue = kombu.Queue(
            exchange=self._exchange,
            bindings=[
                kombu.binding(exchange=self._exchange, arguments=self._arguments)
            ],
            exclusive=True,
        )
        return [Consumer(queue, callbacks=[self._on_message])]


class EventRecorder:
    """Record events published on the Wazo bus to a JSON Lines file.

    Connects directly to RabbitMQ (rather than going through the
    wazo-websocketd websocket) and binds a temporary, exclusive queue to the
    `wazo-headers` exchange using the engine's `origin_uuid`. Every event
    generated by this engine carries that header, so the binding matches them
    all. Each message is written as one JSON object per line.
    """

    def __init__(self, bus_config, output_file, uuid=None):
        self._url = 'amqp://{username}:{password}@{host}:{port}//'.format(**bus_config)
        self._exchange = kombu.Exchange(
            bus_config['exchange_name'],
            type=bus_config['exchange_type'],
        )
        self._output_file = output_file
        self._uuid = find_xivo_uuid(uuid)
        self._connection = None
        self._consumer = None
        self._thread = None
        self._file = None
        self.event_count = 0

    def start(self):
        if not self._uuid:
            logger.error(
                'Could not determine the engine UUID (XIVO_UUID); '
                'bus events will not be recorded'
            )
            return
        self._file = open(self._output_file, 'a')
        self._connection = kombu.Connection(self._url)
        self._consumer = _EventConsumer(
            self._connection,
            self._exchange,
            {'origin_uuid': self._uuid},
            self._on_message,
        )
        self._thread = threading.Thread(
            target=self._run, name='event-recorder', daemon=True
        )
        self._thread.start()

    @property
    def recording(self):
        return self._thread is not None

    def _run(self):
        try:
            if self._consumer is not None:
                self._consumer.run()
        except Exception:
            logger.exception('Event recorder stopped unexpectedly')

    def _on_message(self, body, message):
        headers = message.headers or {}
        record = {
            'timestamp': datetime.now(timezone.utc).isoformat(),
            'name': headers.get('name'),
            'headers': headers,
            'payload': body,
        }
        try:
            line = json.dumps(record, default=str)
        except (TypeError, ValueError):
            logger.exception('Could not serialize bus event %r', headers.get('name'))
            message.ack()
            return
        if self._file is None:
            message.ack()
            return
        self._file.write(line + '\n')
        self._file.flush()
        self.event_count += 1
        message.ack()

    def stop(self):
        if self._consumer:
            self._consumer.should_stop = True
        if self._thread:
            self._thread.join(timeout=10)
        if self._connection:
            self._connection.release()
        if self._thread and not self._thread.is_alive() and self._file is not None:
            self._file.close()
            self._file = None
